### ISSUE TITLE
Archiving on iOS Failed - Several issues with the iOS integration

### ISSUE THREAD

**Issue by atulmy** [razorpay/react-native-razorpay#147]
While Archiving the project for iOS distribution, I'm getting following issues:

<img width="728" alt="screenshot 2019-01-20 at 4 31 24 am" src="https://user-images.githubusercontent.com/685786/51433247-7ebef400-1c6c-11e9-8b43-5c4ac6b9e89e.png">

**Comment by atulmy** [comment]
If anyone is facing this issue, follow these steps:

Xcode -> Select your project on left -> Build Phases -> Click on + -> New Run Script Phases

Copy following [script](http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/):
```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

Click on Xcode -> Product -> Archive.

It should work now. I think these steps should be present in Readme.

These steps are also available in [this](https://www.youtube.com/watch?v=HVGUBRot7VA) this.

**Comment by iThink32** [comment]
@atulmy the video which you referred is present in the docs in a different section.We purposely shifted  it to integration videos as a lot of people prefer watching over reading.Here's the link if you missed it.
https://razorpay.com/docs/ios/integration-videos/
